spring.datasource.url: jdbc:h2:file:./camunda-h2-database
spring.h2.console.enabled: true
camunda.bpm.admin-user:
  id: admin
  password: admin
springdoc:
  swagger-ui:
    urls:
      - url: /camunda/openapi.json
        name: camunda
      - url: /v3/api-docs
        name: example
